BASE <http://example.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT
  ?l_shipmode
WHERE {
  ?order    <o_orderpriority> ?o_orderpriority .
  ?lineitem <l_order>         ?order ;
            <l_shipmode>      ?l_shipmode ;
            <l_commitdate>    ?l_commitdate ;
            <l_receiptdate>   ?l_receiptdate ;
            <l_shipdate>      ?l_shipdate .
  FILTER (?l_shipmode IN ('MAIL', 'AIR') &&
	  ?l_commitdate < ?l_receiptdate &&
	  ?l_shipdate < ?l_commitdate &&
	  ?l_receiptdate >= "1995-01-01T00:00:00"^^xsd:dateTime &&
	  ?l_receiptdate < "1996-01-01T00:00:00"^^xsd:dateTime)
}
