---
title: "R Notebook"
output: html_notebook
---

# Load the data

In this section we load the data and generate the dataframes we analyze throughout this notebook.

We next load the required libraries for the remained of this notebook.

```{r}
library(dplyr)
library(ggplot2)
library(latex2exp)
library(plotrix)
library(scales)
library(plyr)
library(purrr)
library(data.table)
library(stringi)
#remotes::install_github("coolbutuseless/ggpattern")
#library("ggpattern")
library(patternplot)

get.se <- function(y) {
 se <- sd(y)/sqrt(length(y))
 mu <- mean(y)
 c(ymin=mu-se, ymax=mu+se)
}

# ## Summarizes data.
# ## Gives count, mean, standard deviation, standard error of the mean, and confidence interval (default 95%).
# ##   data: a data frame.
# ##   measurevar: the name of a column that contains the variable to be summariezed
# ##   groupvars: a vector containing names of columns that contain grouping variables
# ##   na.rm: a boolean that indicates whether to ignore NA's
# ##   conf.interval: the percent range of the confidence interval (default is 95%)
# summarySE <- function(data=NULL, measurevar, groupvars=NULL, na.rm=FALSE,
#                       conf.interval=.95, .drop=TRUE) {
#     library(plyr)
# 
#     # New version of length which can handle NA's: if na.rm==T, don't count them
#     length2 <- function (x, na.rm=FALSE) {
#         if (na.rm) sum(!is.na(x))
#         else       length(x)
#     }
# 
#     # This does the summary. For each group's data frame, return a vector with
#     # N, mean, and sd
#     datac <- ddply(data, groupvars, .drop=.drop,
#       .fun = function(xx, col) {
#         c(N    = length2(xx[[col]], na.rm=na.rm),
#           mean = mean   (xx[[col]], na.rm=na.rm),
#           sd   = sd     (xx[[col]], na.rm=na.rm)
#         )
#       },
#       measurevar
#     )
# 
#     # Rename the "mean" column    
#     datac <- rename(datac, c("mean" = measurevar))
# 
#     datac$se <- datac$sd / sqrt(datac$N)  # Calculate standard error of the mean
# 
#     # Confidence interval multiplier for standard error
#     # Calculate t-statistic for confidence interval: 
#     # e.g., if conf.interval is .95, use .975 (above/below), and use df=N-1
#     ciMult <- qt(conf.interval/2 + .5, datac$N-1)
#     datac$ci <- datac$se * ciMult
# 
#     return(datac)
# }
```

Load the data.

```{r}
time_results <- 
    list.files(path = "results", pattern = "*.csv", full.names = TRUE) %>% 
    map_df(~fread(.))

time_results$time <- with(time_results, time * 1000)
```

Plot data for query template 01 for Fuseki.

```{r}
select_01 <- filter(time_results,
                    template == 1 & status == 200
                    & !grepl("construct", mode))

p1 <- ggplot(select_01 %>% filter(time < 300000),
             aes(x=scale_factor, y=time, fill=mode)) + 
  facet_wrap(~engine, ncol = 2) +
  stat_summary(fun=mean, geom="bar",
               position=position_dodge(preserve = "single"), color="grey70") +
  scale_x_continuous(trans='log10',
                     labels=trans_format("log10", math_format(10^.x))) +
  scale_y_continuous(trans='log10',
                     labels=trans_format("log10", math_format(10^.x))) +
  xlab("query template") + ylab("time (ms)")

#  geom_bar_pattern(stat = "identity",
#                   pattern_color = "white",
#                   pattern_fill = "black",
#                   aes(pattern = group)) +
  #scale_fill_manual(labels=labs,values=c("#009E73","#CC79A7","#0072B2")) +
#  scale_fill_brewer(palette="OrRd")

p1
```
Plot data for query template 03.

```{r}
select_03 <- filter(time_results,
                    template == 3 & status == 200
                    & !grepl("construct", mode))

p3 <- ggplot(select_03 %>% filter(time < 300000),
             aes(x=scale_factor, y=time, fill=mode)) + 
  facet_wrap(~engine, ncol = 2) +
  stat_summary(fun=mean, geom="bar",
               position=position_dodge(preserve = "single"), color="grey70") +
  scale_x_continuous(trans='log10',
                     labels=trans_format("log10", math_format(10^.x))) +
  scale_y_continuous(trans='log10',
                     labels=trans_format("log10", math_format(10^.x))) +
  xlab("query template") + ylab("time (ms)")

#  geom_bar_pattern(stat = "identity",
#                   pattern_color = "white",
#                   pattern_fill = "black",
#                   aes(pattern = group)) +
  #scale_fill_manual(labels=labs,values=c("#009E73","#CC79A7","#0072B2")) +
#  scale_fill_brewer(palette="OrRd")

p3
```


```{r}
select_05 <- filter(time_results,
                    template == 5 & status == 200
                    & !grepl("construct", mode))

p5 <- ggplot(select_05 %>% filter(time < 300000),
             aes(x=scale_factor, y=time, fill=mode)) + 
  facet_wrap(~engine, ncol = 2) +
  stat_summary(fun=mean, geom="bar",
               position=position_dodge(preserve = "single"), color="grey70") +
  scale_x_continuous(trans='log10',
                     labels=trans_format("log10", math_format(10^.x))) +
  scale_y_continuous(trans='log10',
                     labels=trans_format("log10", math_format(10^.x))) +
  xlab("query template") + ylab("time (ms)")

#  geom_bar_pattern(stat = "identity",
#                   pattern_color = "white",
#                   pattern_fill = "black",
#                   aes(pattern = group)) +
  #scale_fill_manual(labels=labs,values=c("#009E73","#CC79A7","#0072B2")) +
#  scale_fill_brewer(palette="OrRd")

p5
```

```{r}
select_06 <- filter(time_results,
                    template == 6 & status == 200
                    & !grepl("construct", mode))

p6 <- ggplot(select_06 %>% filter(time < 300000),
             aes(x=scale_factor, y=time, fill=mode)) + 
  facet_wrap(~engine, ncol = 2) +
  stat_summary(fun=mean, geom="bar",
               position=position_dodge(preserve = "single"), color="grey70") +
  scale_x_continuous(trans='log10',
                     labels=trans_format("log10", math_format(10^.x))) +
  scale_y_continuous(trans='log10',
                     labels=trans_format("log10", math_format(10^.x))) +
  xlab("query template") + ylab("time (ms)")

#  geom_bar_pattern(stat = "identity",
#                   pattern_color = "white",
#                   pattern_fill = "black",
#                   aes(pattern = group)) +
  #scale_fill_manual(labels=labs,values=c("#009E73","#CC79A7","#0072B2")) +
#  scale_fill_brewer(palette="OrRd")

p6
```





```{r}
select_07 <- filter(time_results,
                    template == 7 & status == 200
                    & !grepl("construct", mode))

p7 <- ggplot(select_07 %>% filter(time < 300000),
             aes(x=scale_factor, y=time, fill=mode)) + 
  facet_wrap(~engine, ncol = 2) +
  stat_summary(fun=mean, geom="bar",
               position=position_dodge(preserve = "single"), color="grey70") +
  scale_x_continuous(trans='log10',
                     labels=trans_format("log10", math_format(10^.x))) +
  scale_y_continuous(trans='log10',
                     labels=trans_format("log10", math_format(10^.x))) +
  xlab("query template") + ylab("time (ms)")

#  geom_bar_pattern(stat = "identity",
#                   pattern_color = "white",
#                   pattern_fill = "black",
#                   aes(pattern = group)) +
  #scale_fill_manual(labels=labs,values=c("#009E73","#CC79A7","#0072B2")) +
#  scale_fill_brewer(palette="OrRd")

p7
```


```{r}
select_08 <- filter(time_results,
                    template == 08 & status == 200
                    & !grepl("construct", mode))

p08 <- ggplot(select_08 %>% filter(time < 300000),
             aes(x=scale_factor, y=time, fill=mode)) + 
  facet_wrap(~engine, ncol = 2) +
  stat_summary(fun=mean, geom="bar",
               position=position_dodge(preserve = "single"), color="grey70") +
  scale_x_continuous(trans='log10',
                     labels=trans_format("log10", math_format(10^.x))) +
  scale_y_continuous(trans='log10',
                     labels=trans_format("log10", math_format(10^.x))) +
  xlab("query template") + ylab("time (ms)")

#  geom_bar_pattern(stat = "identity",
#                   pattern_color = "white",
#                   pattern_fill = "black",
#                   aes(pattern = group)) +
  #scale_fill_manual(labels=labs,values=c("#009E73","#CC79A7","#0072B2")) +
#  scale_fill_brewer(palette="OrRd")

p08
```




```{r}
select_09 <- filter(time_results,
                    template == 9 & status == 200
                    & !grepl("construct", mode))

p09 <- ggplot(select_09 %>% filter(time < 300000),
             aes(x=scale_factor, y=time, fill=mode)) + 
  facet_wrap(~engine, ncol = 2) +
  stat_summary(fun=mean, geom="bar",
               position=position_dodge(preserve = "single"), color="grey70") +
  scale_x_continuous(trans='log10',
                     labels=trans_format("log10", math_format(10^.x))) +
  scale_y_continuous(trans='log10',
                     labels=trans_format("log10", math_format(10^.x))) +
  xlab("query template") + ylab("time (ms)")

#  geom_bar_pattern(stat = "identity",
#                   pattern_color = "white",
#                   pattern_fill = "black",
#                   aes(pattern = group)) +
  #scale_fill_manual(labels=labs,values=c("#009E73","#CC79A7","#0072B2")) +
#  scale_fill_brewer(palette="OrRd")

p09
```




```{r}
select_10 <- filter(time_results,
                    template == 10 & status == 200
                    & !grepl("construct", mode))

p10 <- ggplot(select_10 %>% filter(time < 300000),
             aes(x=scale_factor, y=time, fill=mode)) + 
  facet_wrap(~engine, ncol = 2) +
  stat_summary(fun=mean, geom="bar",
               position=position_dodge(preserve = "single"), color="grey70") +
  scale_x_continuous(trans='log10',
                     labels=trans_format("log10", math_format(10^.x))) +
  scale_y_continuous(trans='log10',
                     labels=trans_format("log10", math_format(10^.x))) +
  xlab("query template") + ylab("time (ms)")

#  geom_bar_pattern(stat = "identity",
#                   pattern_color = "white",
#                   pattern_fill = "black",
#                   aes(pattern = group)) +
  #scale_fill_manual(labels=labs,values=c("#009E73","#CC79A7","#0072B2")) +
#  scale_fill_brewer(palette="OrRd")

p10
```



```{r}
select_12 <- filter(time_results,
                    template == 12 & status == 200
                    & !grepl("construct", mode))

p12 <- ggplot(select_12 %>% filter(time < 300000),
             aes(x=scale_factor, y=time, fill=mode)) + 
  facet_wrap(~engine, ncol = 2) +
  stat_summary(fun=mean, geom="bar",
               position=position_dodge(preserve = "single"), color="grey70") +
  scale_x_continuous(trans='log10',
                     labels=trans_format("log10", math_format(10^.x))) +
  scale_y_continuous(trans='log10',
                     labels=trans_format("log10", math_format(10^.x))) +
  xlab("query template") + ylab("time (ms)")

#  geom_bar_pattern(stat = "identity",
#                   pattern_color = "white",
#                   pattern_fill = "black",
#                   aes(pattern = group)) +
  #scale_fill_manual(labels=labs,values=c("#009E73","#CC79A7","#0072B2")) +
#  scale_fill_brewer(palette="OrRd")

p12
```



```{r}
select_14 <- filter(time_results,
                    template == 14 & status == 200
                    & !grepl("construct", mode))

p14 <- ggplot(select_14 %>% filter(time < 300000),
             aes(x=scale_factor, y=time, fill=mode)) + 
  facet_wrap(~engine, ncol = 2) +
  stat_summary(fun=mean, geom="bar",
               position=position_dodge(preserve = "single"), color="grey70") +
  scale_x_continuous(trans='log10',
                     labels=trans_format("log10", math_format(10^.x))) +
  scale_y_continuous(trans='log10',
                     labels=trans_format("log10", math_format(10^.x))) +
  xlab("query template") + ylab("time (ms)")

#  geom_bar_pattern(stat = "identity",
#                   pattern_color = "white",
#                   pattern_fill = "black",
#                   aes(pattern = group)) +
  #scale_fill_manual(labels=labs,values=c("#009E73","#CC79A7","#0072B2")) +
#  scale_fill_brewer(palette="OrRd")

p14
```


```{r}
select_19 <- filter(time_results,
                    template == 19 & status == 200
                    & !grepl("construct", mode))

p19 <- ggplot(select_19 %>% filter(time < 300000),
             aes(x=scale_factor, y=time, fill=mode)) + 
  facet_wrap(~engine, ncol = 2) +
  stat_summary(fun=mean, geom="bar",
               position=position_dodge(preserve = "single"), color="grey70") +
  scale_x_continuous(trans='log10',
                     labels=trans_format("log10", math_format(10^.x))) +
  scale_y_continuous(trans='log10',
                     labels=trans_format("log10", math_format(10^.x))) +
  xlab("query template") + ylab("time (ms)")

#  geom_bar_pattern(stat = "identity",
#                   pattern_color = "white",
#                   pattern_fill = "black",
#                   aes(pattern = group)) +
  #scale_fill_manual(labels=labs,values=c("#009E73","#CC79A7","#0072B2")) +
#  scale_fill_brewer(palette="OrRd")

p19
```