BASE <http://example.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
CONSTRUCT { <row> <a1> ?revenue }
WHERE {
  SELECT
    (sum(?l_extendedprice * ?l_discount) as ?revenue)
  WHERE {
    ?lineitem <l_extendedprice> ?l_extendedprice ;
              <l_discount>      ?l_discount ;
              <l_shipdate>      ?l_shipdate ;
              <l_quantity>      ?l_quantity .
    FILTER (strdt(concat(str(?l_shipdate), 'T00:00:00'), xsd:dateTime) >= "1995-01-01T00:00:00"^^xsd:dateTime &&
            strdt(concat(str(?l_shipdate), 'T00:00:00'), xsd:dateTime) < "1996-01-01T00:00:00"^^xsd:dateTime &&
            ?l_discount >= 0.01 &&
            ?l_discount <= 0.03 &&
            ?l_quantity < 24)
  }
}
