BASE <http://example.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
CONSTRUCT {
  ?row <a1> ?n_name .
}
WHERE {
  ?customer <c_nation>        ?nation .
  ?order    <o_cust>          ?customer ;
            <o_orderdate>     ?o_orderdate .
  ?lineitem <l_order>         ?order ;
            <l_supp>          ?supplier ;
            <l_extendedprice> ?l_extendedprice ;
            <l_discount>      ?l_discount .
  ?supplier <s_nation>        ?nation .
  ?nation   <n_name>          ?n_name ;
            <n_region>        ?region .
  ?region   <r_name>          "ASIA" .
  FILTER (?o_orderdate >= "1993-01-01T00:00:00"^^xsd:dateTime &&
          ?o_orderdate <  "1994-01-01T00:00:00"^^xsd:dateTime)
  BIND (URI(concat(
    "http://example.org/row/",
    "?s1=", ENCODE_FOR_URI(xsd:string(?n_name))
  )) AS ?row)
}
