BASE <http://example.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
CONSTRUCT {
  ?row
    <a1> ?order ;
    <a2> ?o_orderdate ;
    <a3> ?o_shippriority .
}
WHERE {
  ?customer
    <c_mktsegment> 'FURNITURE' .
  ?order
    <o_cust> ?customer ;
    <o_orderdate> ?o_orderdate ;
    <o_shippriority> ?o_shippriority .
  ?lineitem
    <l_order> ?order ;
    <l_shipdate> ?l_shipdate ;
    <l_extendedprice> ?l_extendedprice ;
    <l_discount> ?l_discount .
  FILTER (?o_orderdate < "1995-03-11T00:00:00"^^xsd:dateTime &&
           ?l_shipdate > "1995-03-11T00:00:00"^^xsd:dateTime)
  BIND (URI(concat(
     "http://example.org/row/",
     "?s1=", ENCODE_FOR_URI(xsd:string(?order)),
     "&s2=", ENCODE_FOR_URI(xsd:string(?o_orderdate)),
     "&s3=", ENCODE_FOR_URI(xsd:string(?o_shippriority))
  )) AS ?row)
}
