BASE <http://example.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT
  ?order
  ?o_orderdate
  ?o_shippriority
WHERE {
   {
     ?customer
       <c_mktsegment> 'HOUSEHOLD' .
     ?order
       <o_cust> ?customer ;
       <o_orderdate> ?o_orderdate ;
       <o_shippriority> ?o_shippriority .
     ?lineitem
       <l_order> ?order ;
       <l_shipdate> ?l_shipdate ;
       <l_extendedprice> ?l_extendedprice ;
       <l_discount> ?l_discount .
   }
   FILTER (strdt(concat(str(?o_orderdate), 'T00:00:00'), xsd:dateTime) < "1995-03-09T00:00:00"^^xsd:dateTime &&
           strdt(concat(str(?l_shipdate), 'T00:00:00'), xsd:dateTime) > "1995-03-09T00:00:00"^^xsd:dateTime)
}
