BASE <http://example.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT
  ?customer
  ?c_name
  ?c_acctbal
  ?n_name
  ?c_address
  ?c_phone
  ?c_comment
  ?p_Sum
  ?p_Sum_summand_Product
  ?p_Sum_summand_Product_factor_1_Statement
  ?p_Sum_summand_Product_factor_2_Statement
  ?p_Sum_summand_Product_factor_3_Statement
  ?p_Sum_summand_Product_factor_4_Statement
WHERE {
  ?customer <c_nation>        ?nation ;
            <c_name>          ?c_name ;
            <c_acctbal>       ?c_acctbal ;
            <c_phone>         ?c_phone ;
            <c_address>       ?c_address ;
            <c_comment>       ?c_comment .
  ?order    <o_cust>          ?customer ;
            <o_orderdate>     ?o_orderdate .
  ?lineitem <l_order>         ?order ;
            <l_extendedprice> ?l_extendedprice ;
            <l_discount>      ?l_discount ;
            <l_returnflag>    'R' .
  ?nation   <n_name>          ?n_name .
  FILTER (?o_orderdate >= "1994-08-01T00:00:00"^^xsd:dateTime &&
          ?o_orderdate < "1994-11-01T00:00:00"^^xsd:dateTime)
  BIND (?customer AS ?p_Sum_summand_Product_factor_1_Statement)
  BIND (?order    AS ?p_Sum_summand_Product_factor_2_Statement)
  BIND (?lineitem AS ?p_Sum_summand_Product_factor_3_Statement)
  BIND (?nation   AS ?p_Sum_summand_Product_factor_4_Statement)
  BIND (URI(concat(
    "http://example.org/p_Sum_summand_Product/",
    "?s1=", ENCODE_FOR_URI(xsd:string(?p_Sum_summand_Product_factor_1_Statement)),
    "&s2=", ENCODE_FOR_URI(xsd:string(?p_Sum_summand_Product_factor_2_Statement)),
    "&s3=", ENCODE_FOR_URI(xsd:string(?p_Sum_summand_Product_factor_3_Statement)),
    "&s4=", ENCODE_FOR_URI(xsd:string(?p_Sum_summand_Product_factor_4_Statement))
  )) AS ?p_Sum_summand_Product)
  BIND (URI(concat(
    "http://example.org/p_Sum/",
    "?s1=", ENCODE_FOR_URI(xsd:string(?customer)),
    "&s2=", ENCODE_FOR_URI(xsd:string(?c_name)),
    "&s3=", ENCODE_FOR_URI(xsd:string(?c_acctbal)),
    "&s4=", ENCODE_FOR_URI(xsd:string(?n_name)),
    "&s4=", ENCODE_FOR_URI(xsd:string(?c_address)),
    "&s4=", ENCODE_FOR_URI(xsd:string(?c_phone)),
    "&s4=", ENCODE_FOR_URI(xsd:string(?c_comment))
  )) AS ?p_Sum)
}
