BASE <http://example.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT
  ?l_returnflag
  ?l_linestatus
  ?p_Sum
  ?p_Sum_summand_Statement
WHERE {
  ?lineitem <l_quantity> ?l_quantity ;
            <l_tax> ?l_tax ;
            <l_shipdate> ?l_shipdate ;
            <l_extendedprice> ?l_extendedprice ;
            <l_discount> ?l_discount ;
            <l_returnflag> ?l_returnflag ;
            <l_linestatus> ?l_linestatus .
  BIND (?lineitem AS ?p_Sum_summand_Statement)
  FILTER (strdt(concat(str(?l_shipdate), 'T00:00:00'), xsd:dateTime) <= "1998-09-16T00:00:00"^^xsd:dateTime)
  BIND (URI(concat(
    "http://example.org/p_Sum/",
    "?s1=", ENCODE_FOR_URI(xsd:string(?l_returnflag)),
    "&s2=", ENCODE_FOR_URI(xsd:string(?l_linestatus))
  )) AS ?p_Sum)
}
