BASE <http://example.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
CONSTRUCT {
  ?row
    <a1> ?order ;
    <a2> ?revenue ;
    <a3> ?o_orderdate ;
    <a4> ?o_shippriority .
}
WHERE {
  {
    SELECT
      ?order
      (sum(?l_extendedprice * (1 - ?l_discount)) AS ?revenue)
      ?o_orderdate
      ?o_shippriority
    WHERE {
       {
         ?customer
           <c_mktsegment> 'FURNITURE' .
         ?order
           <o_cust> ?customer ;
           <o_orderdate> ?o_orderdate ;
           <o_shippriority> ?o_shippriority .
         ?lineitem
           <l_order> ?order ;
           <l_shipdate> ?l_shipdate ;
           <l_extendedprice> ?l_extendedprice ;
           <l_discount> ?l_discount .
       }
       FILTER (strdt(concat(str(?o_orderdate), 'T00:00:00'), xsd:dateTime) < "1995-03-11T00:00:00"^^xsd:dateTime &&
               strdt(concat(str(?l_shipdate), 'T00:00:00'), xsd:dateTime) > "1995-03-11T00:00:00"^^xsd:dateTime)
    }
    GROUP BY ?order ?o_orderdate ?o_shippriority
  }
  BIND (URI(concat(
     "http://example.org/row/",
     "?s1=", ENCODE_FOR_URI(xsd:string(?order)),
     "&s2=", ENCODE_FOR_URI(xsd:string(?o_orderdate)),
     "&s3=", ENCODE_FOR_URI(xsd:string(?o_shippriority))
  )) AS ?row)
}
