BASE <http://example.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT
  (1 AS ?x)
  ?p_Sum
  ?p_Sum_summand_Product
  ?p_Sum_summand_Product_factor_1_Statement
  ?p_Sum_summand_Product_factor_2_Statement
WHERE {
  ?lineitem <l_part>          ?part ;
            <l_quantity>      ?l_quantity ;
            <l_shipmode>      ?l_shipmode ;
            <l_shipinstruct>  ?l_shipinstruct ;
            <l_extendedprice> ?l_extendedprice ;
            <l_discount>      ?l_discount .
  ?part     <p_brand>         ?p_brand ;
            <p_container>     ?p_container ;
            <p_size>          ?p_size .
  FILTER (
    (
      ?p_brand = 'Brand13' &&
      ?p_container IN ('SM CASE', 'SM BOX', 'SM PACK', 'SM PKG') &&
      ?l_quantity >= 1 && ?l_quantity <= 1 + 10 &&
      ?p_size >= 1 && ?p_size <= 5 &&
      ?l_shipmode IN ('AIR', 'AIR REG') &&
      ?l_shipinstruct = 'DELIVER IN PERSON'
    )
    ||
    (
      ?p_brand = 'Brand#21' &&
      ?p_container IN ('MED BAG', 'MED BOX', 'MED PKG', 'MED PACK') &&
      ?l_quantity >= 12 && ?l_quantity <= 12 + 10 &&
      ?p_size >= 1 && ?p_size <= 10 &&
      ?l_shipmode IN ('AIR', 'AIR REG') &&
      ?l_shipinstruct = 'DELIVER IN PERSON'
    )
    ||
    (
      ?p_brand = 'Brand#54' &&
      ?p_container IN ('LG CASE', 'LG BOX', 'LG PACK', 'LG PKG') &&
      ?l_quantity >= 23 && ?l_quantity <= 23 + 10 &&
      ?p_size >= 1 && ?p_size <= 15 &&
      ?l_shipmode IN ('AIR', 'AIR REG') &&
      ?l_shipinstruct = 'DELIVER IN PERSON'
    )
  )
  BIND (?lineitem AS ?p_Sum_summand_Product_factor_1_Statement)
  BIND (?part     AS ?p_Sum_summand_Product_factor_2_Statement)
  BIND (URI(concat(
    "http://example.org/p_Sum_summand_Product/",
    "?s1=", ENCODE_FOR_URI(xsd:string(?p_Sum_summand_Product_factor_1_Statement)),
    "&s2=", ENCODE_FOR_URI(xsd:string(?p_Sum_summand_Product_factor_2_Statement))
  )) AS ?p_Sum_summand_Product)
  BIND (URI("http://example.org/p_Sum/") AS ?p_Sum)
}
