BASE <http://example.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?l_returnflag ?l_linestatus
WHERE {
  ?lineitem <l_quantity>      ?l_quantity ;
            <l_tax>           ?l_tax ;
            <l_shipdate>      ?l_shipdate ;
            <l_extendedprice> ?l_extendedprice ;
            <l_discount>      ?l_discount ;
            <l_returnflag>    ?l_returnflag ;
            <l_linestatus>    ?l_linestatus .
  FILTER (?l_shipdate <= "1998-09-13T00:00:00"^^xsd:dateTime)
}
