BASE <http://example.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX prov: <http://www.w3.org/ns/prov#>
CONSTRUCT {
  ?row
    <a1> ?l_shipmode ;
    <a2> ?high_line_count ;
    <a3> ?low_line_count ;
    prov:wasDerivedFrom ?p_Sum .
  ?p_Sum a <polynomial/Sum> ;
    <polynomial/summand> ?p_Sum_summand_Product .
  ?p_Sum_summand_Product a <polynomial/Product> ;
    <polynomial/factor>
      ?p_Sum_summand_Product_factor_1_Statement ,
      ?p_Sum_summand_Product_factor_2_Statement .
  ?p_Sum_summand_Product_factor_1_Statement a <polynomial/Statement> .
  ?p_Sum_summand_Product_factor_2_Statement a <polynomial/Statement> .
}
WHERE {
  {
    SELECT
      ?l_shipmode
      (sum(if((?o_orderpriority = '1-URGENT' || ?o_orderpriority = '2-HIGH'), 1, 0)) AS ?high_line_count)
      (sum(if((?o_orderpriority != '1-URGENT' && ?o_orderpriority != '2-HIGH'), 1, 0)) AS ?low_line_count)
    WHERE {
      ?order    <o_orderpriority> ?o_orderpriority .
      ?lineitem <l_order>         ?order ;
		<l_shipmode>      ?l_shipmode ;
		<l_commitdate>    ?l_commitdate ;
		<l_receiptdate>   ?l_receiptdate ;
		<l_shipdate>      ?l_shipdate .
      FILTER (?l_shipmode IN ('AIR', 'MAIL') &&
	      strdt(concat(str(?l_commitdate), 'T00:00:00'), xsd:dateTime) < strdt(concat(str(?l_receiptdate), 'T00:00:00'), xsd:dateTime) &&
	      strdt(concat(str(?l_shipdate), 'T00:00:00'), xsd:dateTime) < strdt(concat(str(?l_commitdate), 'T00:00:00'), xsd:dateTime) &&
	      strdt(concat(str(?l_receiptdate), 'T00:00:00'), xsd:dateTime) >= "1994-01-01T00:00:00"^^xsd:dateTime &&
	      strdt(concat(str(?l_receiptdate), 'T00:00:00'), xsd:dateTime) < "1995-01-01T00:00:00"^^xsd:dateTime)
    }
    GROUP BY ?l_shipmode
  } . {
    SELECT
      ?l_shipmode
      ?p_Sum
      ?p_Sum_summand_Product
      ?p_Sum_summand_Product_factor_1_Statement
      ?p_Sum_summand_Product_factor_2_Statement
    WHERE {
      ?order    <o_orderpriority> ?o_orderpriority .
      ?lineitem <l_order>         ?order ;
		<l_shipmode>      ?l_shipmode ;
		<l_commitdate>    ?l_commitdate ;
		<l_receiptdate>   ?l_receiptdate ;
		<l_shipdate>      ?l_shipdate .
      FILTER (?l_shipmode IN ('AIR', 'MAIL') &&
	      strdt(concat(str(?l_commitdate), 'T00:00:00'), xsd:dateTime) < strdt(concat(str(?l_receiptdate), 'T00:00:00'), xsd:dateTime) &&
	      strdt(concat(str(?l_shipdate), 'T00:00:00'), xsd:dateTime) < strdt(concat(str(?l_commitdate), 'T00:00:00'), xsd:dateTime) &&
	      strdt(concat(str(?l_receiptdate), 'T00:00:00'), xsd:dateTime) >= "1994-01-01"^^xsd:dateTime &&
	      strdt(concat(str(?l_receiptdate), 'T00:00:00'), xsd:dateTime) < "1995-01-01"^^xsd:dateTime)
      BIND (?order    AS ?p_Sum_summand_Product_factor_1_Statement)
      BIND (?lineitem AS ?p_Sum_summand_Product_factor_2_Statement)
      BIND (URI(concat(
        "http://example.org/p_Sum_summand_Product/",
        "?s1=", ENCODE_FOR_URI(xsd:string(?p_Sum_summand_Product_factor_1_Statement)),
        "&s2=", ENCODE_FOR_URI(xsd:string(?p_Sum_summand_Product_factor_2_Statement))
      )) AS ?p_Sum_summand_Product)
      BIND (URI(concat(
        "http://example.org/p_Sum/",
        "?s1=", ENCODE_FOR_URI(xsd:string(?l_shipmode))
      )) AS ?p_Sum)
    }
  }
  BIND (URI(concat(
    "http://example.org/row/",
    "?s1=", ENCODE_FOR_URI(xsd:string(?l_shipmode))
  )) AS ?row)
}
