BASE <http://example.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT
  ?l_shipmode
  (sum(if((?o_orderpriority = '1-URGENT' || ?o_orderpriority = '2-HIGH'), 1, 0)) AS ?high_line_count)
  (sum(if((?o_orderpriority != '1-URGENT' && ?o_orderpriority != '2-HIGH'), 1, 0)) AS ?low_line_count)
WHERE {
  ?order    <o_orderpriority> ?o_orderpriority .
  ?lineitem <l_order>         ?order ;
            <l_shipmode>      ?l_shipmode ;
            <l_commitdate>    ?l_commitdate ;
            <l_receiptdate>   ?l_receiptdate ;
            <l_shipdate>      ?l_shipdate .
  FILTER (?l_shipmode IN ("TRUCK", "RAIL") &&
          strdt(concat(str(?l_commitdate), 'T00:00:00'), xsd:dateTime) < strdt(concat(str(?l_receiptdate), 'T00:00:00'), xsd:dateTime) &&
          strdt(concat(str(?l_shipdate), 'T00:00:00'), xsd:dateTime) < strdt(concat(str(?l_commitdate), 'T00:00:00'), xsd:dateTime) &&
          strdt(concat(str(?l_receiptdate), 'T00:00:00'), xsd:dateTime) >= "1995-01-01T00:00:00"^^xsd:dateTime &&
          strdt(concat(str(?l_receiptdate), 'T00:00:00'), xsd:dateTime) < "1996-01-01T00:00:00"^^xsd:dateTime)
}
GROUP BY ?l_shipmode
