BASE <http://example.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX prov: <http://www.w3.org/ns/prov#>
CONSTRUCT {
  <row>
    <a1> ?revenue ;
    prov:wasDerivedFrom ?p_Sum .
  ?p_Sum a <polynomial/Sum> ;
    <polynomial/summand> ?p_Sum_summand_Statement .
  ?p_Sum_summand_Statement a <polynomial/statement> .
}
WHERE {
  SELECT
    ?revenue
    ?p_Sum
    ?p_Sum_summand_Statement
  WHERE {
    {
      SELECT
        (sum(?l_extendedprice * ?l_discount) as ?revenue)
      WHERE {
        ?lineitem <l_extendedprice> ?l_extendedprice ;
                  <l_discount>      ?l_discount ;
                  <l_shipdate>      ?l_shipdate ;
                  <l_quantity>      ?l_quantity .
        FILTER (strdt(concat(str(?l_shipdate), 'T00:00:00'), xsd:dateTime) >= "1995-01-01T00:00:00"^^xsd:dateTime &&
                strdt(concat(str(?l_shipdate), 'T00:00:00'), xsd:dateTime) < "1996-01-01T00:00:00"^^xsd:dateTime &&
                ?l_discount >= 0.07 &&
                ?l_discount <= 0.09 &&
                ?l_quantity < 25)
      }
    } . {
      SELECT
        ?p_Sum
        ?p_Sum_summand_Statement
      WHERE {
        ?lineitem <l_extendedprice> ?l_extendedprice ;
                  <l_discount>      ?l_discount ;
                  <l_shipdate>      ?l_shipdate ;
                  <l_quantity>      ?l_quantity .
        FILTER (strdt(concat(str(?l_shipdate), 'T00:00:00'), xsd:dateTime) >= "1995-01-01T00:00:00"^^xsd:dateTime &&
                strdt(concat(str(?l_shipdate), 'T00:00:00'), xsd:dateTime) < "1996-01-01T00:00:00"^^xsd:dateTime &&
                ?l_discount >= 0.07 &&
                ?l_discount <= 0.09 &&
                ?l_quantity < 25)
        BIND (?lineitem AS ?p_Sum_summand_Statement)
        BIND (URI("http://example.org/p_Sum/") AS ?p_Sum)
      }
    }
  }
}
